# Homework 3  - Tryout pandas and numpy

Copy this notebook. Rename it as: YOURNAME-Homework-panda-numpy-Sept-2017

with your name replacing yourname and  replaced with the date you submit or to the last part.

Do the homeworks problems below.

Upload your completed jupyter notebook to your github site and send me the url via the elearning site as your homework submission. Please note that you need to do your own 3.4, and 3.5 if you share data and analysis from others then you cannot get more than a 3.  

## Homework 3.1

### 3.1.a
Load the data from: http://opendata.dc.gov/datasets that I have include in this github   
into a dataframe.  ( The file has been is available in directory ./data/ccp_current_csv.csv )

In [66]:
import pandas as pd
daf = pd.read_csv('ccp_current_csv.csv')
daf

STREET QUADRANT            FROMINTERSECTION  \
0               13th St       NW                  Kennedy St   
1                  S St       NW            North Capitol St   
2      Rhode Island Ave       NE            Brentwood Rd (W)   
3               Mill Rd       NW                     27th St   
4      Rhode Island Ave       NE            Brentwood Rd (M)   
5             Mellon St       SE                      5th St   
6          Nebraska Ave       NW              Northampton St   
7           Military Rd       NW                     30th St   
8          Nebraska Ave       NW                   Oliver St   
9               16th St       NW                  Alaska Ave   
10         Shoemaker St       NW                 Linnean Ave   
11         Underwood St       NW             Piney Branch Rd   
12             Elder St       NW                      7th St   
13              26th St       NW              Northampton St   
14               4th St       NW              Madison St (N)   
15         Underwood Pl       NW            North Capitol St   
16              20th St       NW                 Columbia Rd   
17          Quintana Pl       NE                      3rd St   
18         Tuckerman St       NE                  Kansas Ave   
19              Eads St       NE                     45th St   
20               4th St       SE                  Newcomb St   
21              Belt Rd       NW                  Jenifer St   
22            Oneida St       NE           New Hampshire Ave   
23      Carrollsburg Pl       SW                        O St   
24              23rd St       NW          Washington Cir (N)   
25           Kanawha St       NW                    Utah Ave   
26      Piney Branch Rd       NW                Underwood St   
27              30th St       NW               Stephenson Pl   
28              32nd St       NW                 Woodland Dr   
29              33rd St       NW            Broad Branch Ter   
..                  ...      ...                         ...   
435      New Jersey Ave       NW                        F St   
436             15th St       NE                     Ames Pl   
437     East Capitol St       BN                        C St   
438         Randolph St       NE                     25th Pl   
439    South Dakota Ave       NE                Delafield St   
440          Wheeler Rd       SE                 Congress St   
441      New Jersey Ave       NW                        H St   
442     Mount Olivet Rd       NE               Brentwood Pky   
443              Oak St       NW                     16th St   
444        Michigan Ave       NE                     14th St   
445                C St       NE                     20th St   
446        Virginia Ave       SE                  6th St (S)   
447              Oak St       NW                Brown St (N)   
448         Florida Ave       NE                New York Ave   
449  North Carolina Ave       NE         East Capitol St (E)   
450            Elder St       NW                      8th St   
451          Benning Rd       SE                        G St   
452           School St       SW                      4th St   
453             18th St       NW                        M St   
454       Longfellow St       NW                     16th St   
455             10th St       NW                        M St   
456          Woodley Rd       NW             Connecticut Ave   
457          Woodley Rd       NW           Cathedral Ave (E)   
458              3rd St       SW            Independence Ave   
459             16th St       NW                 Primrose Rd   
460          Woodley Rd       NW                  Woodley Pl   
461         Western Ave       NW         Chevy Chase Cir (E)   
462             49th St       NW                   Fulton St   
463       Quackenbos St       NE           New Hampshire Ave   
464    North Capitol St       BN  Hawaii Ave  Rock Creek Chu   

                 TOINTERSECTION  NOOFBLOCKS     

### 3.1.a  what is its shape and what does that mean?

In [67]:
daf.shape

(465, 27)

In [ ]:
465, 27 means that it has 465 rows and 27 columns

## Homework 3.2
 What are the number of rows in each 'QUADRANT' ?

In [74]:
daf.QUADRANT.value_counts()

NW    195
NE    163
SE     84
BN     12
SW     11
Name: QUADRANT, dtype: int64

## Homework 3.3 - Array math demonstration 
For two arrarys  

a= [1,2,3,4]  type=float

b= [5,6,7,8]  type=float

Peform the following array operations using numpy   
( show both operational use of numpy and functional (example addition operation => + vs addition function => numbpy.add() )

### 3.3.1 addition a+b 

Let us look at the difference between a '+' and numpy.add() 

In [8]:
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]
a + b

[1, 2, 3, 4, 5, 6, 7, 8]

In [9]:
import numpy
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]
numpy.add(a, b)

array([ 6,  8, 10, 12])

### 3.3.2 subtraction a-b

In [11]:
import numpy
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]
numpy.subtract(a, b)

array([-4, -4, -4, -4])

### 3.3.3 multiplication a*b

In [13]:
import numpy
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]
numpy.multiply(a, b)

array([ 5, 12, 21, 32])

### 3.3.4 divsion a/b

In [15]:
import numpy
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]
numpy.divide(b, a)

array([5, 3, 2, 2])

### 3.3.5 modulo  a%b

In [21]:
import numpy
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]
numpy.remainder(b, a)

array([0, 0, 1, 0])

### 3.3.6 power  a^b

In [22]:
import numpy
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]
numpy.power(b, a)

array([   5,   36,  343, 4096])

In [23]:
import numpy
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]
numpy.power(a, b)

array([    1,    64,  2187, 65536])

Homework 3.4
Find your own data and load it into a dataframe

I have downloaded sample data from the internet.

In [42]:
import pandas as pd
df = pd.read_csv('SampleCSVFile_11kb.csv')
df

1   Eldon Base for stackable storage shelf, platinum Muhammed MacIntyre  \
0     2  1.7 Cubic Foot Compact "Cube" Office Refrigera...       Barry French   
1     3   Cardinal Slant-D� Ring Binder, Heavy Gauge Vinyl       Barry French   
2     4                                               R380      Clay Rozendal   
3     5                           Holmes HEPA Air Purifier     Carlos Soltero   
4     6  G.E. Longer-Life Indoor Recessed Floodlight Bulbs     Carlos Soltero   
5     7  Angle-D Binders with Locking Rings, Label Holders       Carl Jackson   
6     8            SAFCO Mobile Desk Side File, Wire Frame       Carl Jackson   
7     9              SAFCO Commercial Wire Shelving, Black     Monica Federle   
8    10                                          Xerox 198    Dorothy Badders   
9    11                                         Xerox 1980    Neola Schneider   
10   12    Advantus Map Pennant Flags and Round Head Tacks    Neola Schneider   
11   13                           Holmes HEPA Air Purifier        Carlos Daly   
12   14  DS/HD IBM Formatted Diskettes, 200/Pack - Staples        Carlos Daly   
13   15     Wilson Jones 1" Hanging DublLock� Ring Binders      Claudia Miner   
14   16      Ultra Commercial Grade Dual Valve Door Closer    Neola Schneider   
15   17  #10-4 1/8" x 9 1/2" Premium Diagonal Seam Enve...   Allen Rosenblatt   
16   18                        Hon 4-Shelf Metal Bookcases    Sylvia Foulston   
17   19  Lesro Sheffield Collection Coffee Table, End T...    Sylvia Foulston   
18   20                                               g520        Jim Radford   
19   21                                             LX 788        Jim Radford   
20   22                                           Avery 52     Carlos Soltero   
21   23            Plymouth Boxed Rubber Bands by Plymouth     Carlos Soltero   
22   24  GBC Pre-Punched Binding Paper, Plastic, White,...        Carl Ludwig   
23   25  Maxell 3.5" DS/HD IBM-Formatted Diskettes, 10/...        Carl Ludwig   
24   26                                         Newell 335         Don Miller   
25   27     SANFORD Liquid Accent� Tank-Style Highlighters       Annie Cyprus   
26   28                                 Canon PC940 Copier        Carl Ludwig   
27   29  Tenex Personal Project File with Scoop Front D...     Carlos Soltero   
28   30                    Col-Erase� Pencils with Erasers      Grant Carroll   
29   31  Imation 3.5" DS/HD IBM Formatted Diskettes, 10...         Don Miller   
..  ...                                                ...                ...   
69   71                   12-1/2 Diameter Round Wall Clock     Dorothy Wardle   
70   72                           SAFCO Arco Folding Chair      Grant Carroll   
71   73         #10 White Business Envelopes,4 1/8 x 9 1/2      Barry Weirich   
72   74                              3M Office Air Cleaner         Beth Paige   
73   75      Global Leather and Oak Executive Chair, Black    Sylvia Foulston   
74   76                                         Xerox 1936      Nicole Hansen   
75   77                                          Xerox 214      Nicole Hansen   
76   78  Carina Double Wide Media Storage Towers in Nat...      Nicole Hansen   
77   79                Staples� General Use 3-Ring Binders         Beth Paige   
78   80                                         Xerox 1904         Beth Paige   
79   81       Luxo Professional Combination Clamp-On Lamps         Beth Paige   
80   82                                          Xerox 217         Beth Paige   
81   83                Revere Boxed Rubber Bands by Revere         Beth Paige   
82   84  Acco Smartsocket� Table Surge Protector, 6 Col...    Sylvia Foulston   
83   85  Tennsco Snap-Together Open Shelving Units, Sta...        Bryan Davis   
84   86  Hon 4070 Series Pagoda� Round Back Stacking Ch...           Joy Bell   
85   87                                         Xerox 1887           Joy Bell   
86   88                              

## Homework 3.5
Provide an interesting analysis of the data columns ( frequency or averages )

In [43]:
df.info()
#to display the information about each column, we can use .info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 10 columns):
1                                                   99 non-null int64
Eldon Base for stackable storage shelf, platinum    99 non-null object
Muhammed MacIntyre                                  99 non-null object
3                                                   99 non-null int64
-213.25                                             99 non-null float64
38.94                                               99 non-null float64
35                                                  99 non-null float64
Nunavut                                             99 non-null object
Storage & Organization                              99 non-null object
0.8                                                 96 non-null float64
dtypes: float64(4), int64(2), object(4)
memory usage: 7.8+ KB


In [44]:
df.head(10)
#Displays only the first 10 rows

1   Eldon Base for stackable storage shelf, platinum Muhammed MacIntyre  \
0   2  1.7 Cubic Foot Compact "Cube" Office Refrigera...       Barry French   
1   3   Cardinal Slant-D� Ring Binder, Heavy Gauge Vinyl       Barry French   
2   4                                               R380      Clay Rozendal   
3   5                           Holmes HEPA Air Purifier     Carlos Soltero   
4   6  G.E. Longer-Life Indoor Recessed Floodlight Bulbs     Carlos Soltero   
5   7  Angle-D Binders with Locking Rings, Label Holders       Carl Jackson   
6   8            SAFCO Mobile Desk Side File, Wire Frame       Carl Jackson   
7   9              SAFCO Commercial Wire Shelving, Black     Monica Federle   
8  10                                          Xerox 198    Dorothy Badders   
9  11                                         Xerox 1980    Neola Schneider   

     3  -213.25   38.94     35  Nunavut          Storage & Organization   0.8  
0  293   457.81  208.16  68.02  Nunavut                      Appliances  0.58  
1  293    46.71    8.69   2.99  Nunavut  Binders and Binder Accessories  0.39  
2  483  1198.97  195.99   3.99  Nunavut    Telephones and Communication  0.58  
3  515    30.94   21.78   5.94  Nunavut                      Appliances  0.50  
4  515     4.43    6.64   4.95  Nunavut              Office Furnishings  0.37  
5  613   -54.04    7.30   7.72  Nunavut  Binders and Binder Accessories  0.38  
6  613   127.70   42.76   6.22  Nunavut          Storage & Organization   NaN  
7  643  -695.26  138.14  35.00  Nunavut          Storage & Organization   NaN  
8  678  -226.36    4.98   8.33  Nunavut                           Paper  0.38  
9  807  -166.85    4.28   6.18  Nunavut                           Paper  0.40

************************************************************************************************************
Let us group the data by the "Storage and Organization"
************************************************************************************************************

In [45]:
f = df.groupby("Storage & Organization").sum()
f

1       3  -213.25    38.94      35   0.8
Storage & Organization                                                      
Appliances                       280   29214  1335.47   424.71  142.76  3.78
Binders and Binder Accessories   474   46991  -608.85   140.95   65.47  4.12
Bookcases                        178   18063  -168.18   342.94  137.08  2.03
Chairs & Chairmats               438   43461  9585.03  1834.15  296.58  3.51
Computer Peripherals             317   29540  1015.89   222.05   25.39  4.36
Copiers and Fax                   28    1761  -547.61   449.99   49.00  0.38
Envelopes                         90    8428   447.00    31.41    2.78  0.78
Labels                           235   22515   329.34    21.76    2.49  1.88
Office Furnishings               382   39516  1178.74   304.67  105.56  3.75
Paper                           1285  132475   191.41   295.53  133.59  7.81
Pens & Art Supplies              342   33376   108.63    61.55   16.59  3.23
Rubber Bands                     118   11214   -41.59    10.55    3.46  2.16
Scissors, Rulers and Trimmers     61    6116 -1759.58  1637.53   24.49  0.81
Storage & Organization           276   27924 -1890.50   565.74  123.19  2.79
Tables                           114   11653  -449.83   333.48  131.74  1.43
Telephones and Communication     431   41440  1940.03  1026.90   54.93  6.31

************************************************************************************************************
Let us find out the how many different kinds of storage & organisation entries are there.
Since we have already grouped by that coloumn, we could just find out the length of the grouped sub frame.
************************************************************************************************************

In [28]:
len(f)

16

******************************************************************************************************
Let us sort the Storage & Organization entries according to the weight of the corresponding value of "1" coloumn. (from highest to lowest)
******************************************************************************************************

In [55]:
f.sort_values("1", ascending = 0)

1       3  -213.25    38.94      35   0.8
Storage & Organization                                                      
Paper                           1285  132475   191.41   295.53  133.59  7.81
Binders and Binder Accessories   474   46991  -608.85   140.95   65.47  4.12
Chairs & Chairmats               438   43461  9585.03  1834.15  296.58  3.51
Telephones and Communication     431   41440  1940.03  1026.90   54.93  6.31
Office Furnishings               382   39516  1178.74   304.67  105.56  3.75
Pens & Art Supplies              342   33376   108.63    61.55   16.59  3.23
Computer Peripherals             317   29540  1015.89   222.05   25.39  4.36
Appliances                       280   29214  1335.47   424.71  142.76  3.78
Storage & Organization           276   27924 -1890.50   565.74  123.19  2.79
Labels                           235   22515   329.34    21.76    2.49  1.88
Bookcases                        178   18063  -168.18   342.94  137.08  2.03
Rubber Bands                     118   11214   -41.59    10.55    3.46  2.16
Tables                           114   11653  -449.83   333.48  131.74  1.43
Envelopes                         90    8428   447.00    31.41    2.78  0.78
Scissors, Rulers and Trimmers     61    6116 -1759.58  1637.53   24.49  0.81
Copiers and Fax                   28    1761  -547.61   449.99   49.00  0.38

***********************************************************************************************************
Let us find the 'Storage & Organisation element' that has the highest cumulative sum of each coloumn.
***********************************************************************************************************

In [59]:
f.idxmax()

1                       Paper
3                       Paper
-213.25    Chairs & Chairmats
38.94      Chairs & Chairmats
35         Chairs & Chairmats
0.8                     Paper
dtype: object

***********************************************************************************************************
Let us find out the average value in the coloumn '1' from the original data frame
***********************************************************************************************************

In [61]:
df.mean()['1']

51.0